# Main colors
background            #0c141b
foreground            #dce3ed
cursor                #dce3ed
cursor_text_color     #0c141b
selection_background  #384764
selection_foreground  #d7e2ff
url_color             #bfc2fa

# ANSI colors
color0                #0c141b
color1                #ffb4ab
color2                #bfc2fa
color3                #b7c7ea
color4                #94ccff
color5                #bfc2fa
color6                #b7c7ea
color7                #dce3ed
color8                #404850
color9                #93000a
color10               #3e4372
color11               #384764
color12               #004b74
color13               #384764
color14               #3e4372
color15               #c0c7d1

# Starship prompt bubbles
color255              #004b74
color254              #94ccff
color253              #384764
color252              #b7c7ea
color251              #3e4372
color250              #bfc2fa
color249              #93000a
color248              #ffb4ab
color232              #cde5ff
color233              #003352
color234              #d7e2ff
color235              #21304c
color236              #e0e0ff
color237              #282c5a
color238              #ffdad6
color239              #690005
color240              #cde5ff
color243              #94ccff
color244              #ffb4ab
color245              #404850

# UI elements
active_tab_foreground   #003352
active_tab_background   #94ccff
inactive_tab_foreground #cde5ff
inactive_tab_background #004b74
active_border_color     #94ccff
inactive_border_color   #8a919b

# Marks
mark1_foreground        #001d32
mark1_background        #cde5ff
mark2_foreground        #0a1b36
mark2_background        #d7e2ff
mark3_foreground        #121644
mark3_background        #e0e0ff
