# Matugen — kitty 主题（clavis 统一主题管线）
background #1e100e
foreground #f9dcd8
cursor #ffb4ab
selection_background #930009
selection_foreground #ffdad5

color0 #1e100e
color1 #ffb4ab
color2 #ffb4ab
color3 #fab982
color4 #f4b9a0
color5 #930009
color6 #ffdad5
color7 #f9dcd8
color8 #473533
color9 #ffb4ab
color10 #ffb4ab
color11 #fab982
color12 #f4b9a0
color13 #930009
color14 #ffdad5
color15 #f9dcd8
