# Matugen — kitty 主题（clavis 统一主题管线）
background #1e100b
foreground #f9ddd3
cursor #ffb598
selection_background #7e2c00
selection_foreground #ffdbce

color0 #1e100b
color1 #ffb4ab
color2 #ffb598
color3 #efbe79
color4 #efbc95
color5 #7e2c00
color6 #ffdbce
color7 #f9ddd3
color8 #47352f
color9 #ffb4ab
color10 #ffb598
color11 #efbe79
color12 #efbc95
color13 #7e2c00
color14 #ffdbce
color15 #f9ddd3
