# Matugen — kitty 主题（clavis 统一主题管线）
background #1d1012
foreground #f7dcde
cursor #ffb2bc
selection_background #910035
selection_foreground #ffd9dd

color0 #1d1012
color1 #ffb4ab
color2 #ffb2bc
color3 #ffb693
color4 #f6b8ae
color5 #910035
color6 #ffd9dd
color7 #f7dcde
color8 #463537
color9 #ffb4ab
color10 #ffb2bc
color11 #ffb693
color12 #f6b8ae
color13 #910035
color14 #ffd9dd
color15 #f7dcde
